version: '3'

services:
 nginx:
  image: nginx:alpine
  ports:
   - 80:80
  volumes:
   - ./public_html:/public_html
   - ./conf.d:/etc/nginx/conf.d
  networks:
   - nginxphp
  links:
   - php:php
 php:
  image: itdevgroup/php-fpm7.4
  volumes:
   - ./public_html:/public_html
  ports:
   - 9000
  networks:
   - nginxphp
  links:
   - db:db
   - redis:redis
 db:
  image: mysql
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: root1234
  networks:
   - nginxphp
  
 redis:
  image: redis
  ports:
   - "6379:6379"
  networks:
   - nginxphp
  container_name: rediscon
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
   - '8080:80'
  links:
   - db
  networks:
   - nginxphp
networks:
 nginxphp:
  driver: bridge

